import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'de' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  translateField: (type: 'cuisine' | 'difficulty' | 'cookingTime' | 'category' | 'ingredient', value: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  de: {
    // Navigation
    'nav.brand': 'The Pantry',
    'nav.dishCollection': 'Gerichte-Sammlung',
    'nav.weeklyPlanner': 'Wochenplaner',
    'nav.hello': 'Hallo',
    'nav.logout': 'Abmelden',
    'nav.login': 'Anmelden',
    
    // Hero Section
    'hero.title': 'Willkommen in The Pantry',
    'hero.subtitle': 'Ihre kulinarische Reise beginnt hier. Entdecken Sie köstliche Rezepte, planen Sie Ihre Mahlzeiten und lassen Sie sich von unserer Auswahl inspirieren.',
    'hero.cta': 'Entdecken Sie Rezepte',
    
    // Categories
    'categories.title': 'Gerichte entdecken',
    'categories.dishCollection.title': 'Gerichte-Sammlung',
    'categories.dishCollection.description': 'Durchstöbern Sie unsere komplette Sammlung köstlicher Gerichte',
    'categories.dishOfDay.title': 'Gericht des Tages',
    'categories.dishOfDay.description': 'Entdecken Sie das heutige besondere Gericht',
    'categories.ingredientFinder.title': 'Zutatenfinder',
    'categories.ingredientFinder.description': 'Finden Sie Rezepte mit Ihren verfügbaren Zutaten',
    'categories.weeklyCalendar.title': 'Wochenkalender',
    'categories.weeklyCalendar.description': 'Planen und verwalten Sie Ihre Mahlzeiten der Woche',
    
    // Dish Library
    'dishLibrary.title': 'Gerichte-Sammlung',
    'dishLibrary.search': 'Gerichte durchsuchen...',
    'dishLibrary.filters.cuisine': 'Küche',
    'dishLibrary.filters.cookingTime': 'Kochzeit',
    'dishLibrary.filters.difficulty': 'Schwierigkeit',
    'dishLibrary.filters.category': 'Kategorie',
    'dishLibrary.filters.all': 'Alle',
    'dishLibrary.filters.quick': 'Schnell (<30 Min)',
    'dishLibrary.filters.medium': 'Mittel (30-60 Min)',
    'dishLibrary.filters.long': 'Lang (>60 Min)',
    'dishLibrary.filters.easy': 'Einfach',
    'dishLibrary.filters.hard': 'Schwer',
    'dishLibrary.clearFilters': 'Filter zurücksetzen',
    'dishLibrary.results': 'Gerichte gefunden',
    'dishLibrary.noResults': 'Keine Gerichte gefunden',
    'dishLibrary.noResultsDescription': 'Versuchen Sie andere Suchbegriffe oder setzen Sie die Filter zurück.',
    
    // Dish of the Day
    'dishOfDay.title': 'Gericht des Tages',
    'dishOfDay.subtitle': 'Heute empfehlen wir Ihnen dieses besondere Gericht',
    'dishOfDay.cookingTime': 'Kochzeit',
    'dishOfDay.difficulty': 'Schwierigkeit',
    'dishOfDay.cuisine': 'Küche',
    'dishOfDay.category': 'Kategorie',
    'dishOfDay.ingredients': 'Zutaten',
    
    // Ingredient Finder
    'ingredientFinder.title': 'Zutatenfinder',
    'ingredientFinder.subtitle': 'Wählen Sie Ihre verfügbaren Zutaten aus und entdecken Sie passende Gerichte',
    'ingredientFinder.search': 'Zutaten suchen...',
    'ingredientFinder.selected': 'Ausgewählte Zutaten',
    'ingredientFinder.clear': 'Alle löschen',
    'ingredientFinder.results': 'Passende Gerichte',
    'ingredientFinder.noIngredients': 'Keine Zutaten ausgewählt',
    'ingredientFinder.selectIngredients': 'Wählen Sie Zutaten aus, um passende Gerichte zu finden.',
    
    // Weekly Calendar
    'weeklyCalendar.title': 'Wochenkalender',
    'weeklyCalendar.subtitle': 'Planen Sie Ihre Mahlzeiten für die Woche',
    'weeklyCalendar.save': 'Wochenplan speichern',
    'weeklyCalendar.clear': 'Woche löschen',
    'weeklyCalendar.connectSupabase': 'Um Ihren Wochenplan zu speichern, müssen Sie sich anmelden.',
    'weeklyCalendar.loginRequired': 'Anmeldung erforderlich',
    'weeklyCalendar.saved': 'Wochenplan erfolgreich gespeichert!',
    'weeklyCalendar.cleared': 'Wochenplan erfolgreich gelöscht!',
    'weeklyCalendar.error': 'Fehler beim Speichern des Wochenplans',
    'weeklyCalendar.days.monday': 'Montag',
    'weeklyCalendar.days.tuesday': 'Dienstag',
    'weeklyCalendar.days.wednesday': 'Mittwoch',
    'weeklyCalendar.days.thursday': 'Donnerstag',
    'weeklyCalendar.days.friday': 'Freitag',
    'weeklyCalendar.days.saturday': 'Samstag',
    'weeklyCalendar.days.sunday': 'Sonntag',
    'weeklyCalendar.selectDish': 'Gericht auswählen...',
    'weeklyCalendar.personal': 'Persönlicher Kalender',
    'weeklyCalendar.selectGroup': 'Gruppe wählen',
    
    // Groups
    'groups.title': 'Meine Gruppen',
    'groups.subtitle': 'Verwalten Sie Ihre Gruppen und teilen Sie Wochenpläne',
    'groups.createGroup': 'Neue Gruppe erstellen',
    'groups.joinGroup': 'Gruppe beitreten',
    'groups.myGroups': 'Meine Gruppen',
    'groups.noGroups': 'Keine Gruppen',
    'groups.noGroupsDescription': 'Erstellen Sie eine neue Gruppe oder treten Sie mit einem Einladungscode bei.',
    'groups.members': 'Mitglieder',
    'groups.inviteCode': 'Einladungscode',
    'groups.copyCode': 'Code kopieren',
    'groups.codeCopied': 'Code kopiert!',
    'groups.creator': 'Ersteller',
    'groups.member': 'Mitglied',
    'groups.leaveGroup': 'Gruppe verlassen',
    'groups.deleteGroup': 'Gruppe löschen',
    'groups.leaveConfirm': 'Möchten Sie diese Gruppe wirklich verlassen?',
    'groups.deleteConfirm': 'Möchten Sie diese Gruppe wirklich löschen? Dies kann nicht rückgängig gemacht werden.',
    'groups.left': 'Gruppe erfolgreich verlassen',
    'groups.deleted': 'Gruppe erfolgreich gelöscht',
    'groups.error': 'Fehler beim Laden der Gruppen',
    
    // Create Group Dialog
    'createGroup.title': 'Neue Gruppe erstellen',
    'createGroup.description': 'Erstellen Sie eine Gruppe, um Wochenpläne mit anderen zu teilen.',
    'createGroup.nameLabel': 'Gruppenname',
    'createGroup.namePlaceholder': 'z.B. Familie, WG, Freunde',
    'createGroup.cancel': 'Abbrechen',
    'createGroup.create': 'Erstellen',
    'createGroup.success': 'Gruppe erfolgreich erstellt!',
    'createGroup.error': 'Fehler beim Erstellen der Gruppe',
    
    // Join Group Dialog
    'joinGroup.title': 'Gruppe beitreten',
    'joinGroup.description': 'Geben Sie einen Einladungscode ein, um einer Gruppe beizutreten.',
    'joinGroup.codeLabel': 'Einladungscode',
    'joinGroup.codePlaceholder': 'Geben Sie den Code ein',
    'joinGroup.cancel': 'Abbrechen',
    'joinGroup.join': 'Beitreten',
    'joinGroup.success': 'Erfolgreich der Gruppe beigetreten!',
    'joinGroup.invalidCode': 'Ungültiger Einladungscode',
    'joinGroup.alreadyMember': 'Sie sind bereits Mitglied dieser Gruppe',
    'joinGroup.error': 'Fehler beim Beitreten der Gruppe',
    
    // Auth
    'auth.title': 'Anmeldung',
    'auth.login': 'Anmelden',
    'auth.signup': 'Registrieren',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.confirmPassword': 'Passwort bestätigen',
    'auth.loginButton': 'Anmelden',
    'auth.signupButton': 'Registrieren',
    'auth.switchToSignup': 'Noch kein Konto? Registrieren',
    'auth.switchToLogin': 'Bereits ein Konto? Anmelden',
    'auth.loginSuccess': 'Erfolgreich angemeldet!',
    'auth.signupSuccess': 'Erfolgreich registriert!',
    'auth.error': 'Anmeldung fehlgeschlagen',
    'auth.backToHome': 'Zurück zur Startseite',
    
    // Add Dish Dialog
    'addDish.button': 'Eigenes Gericht hinzufügen',
    'addDish.title': 'Neues Gericht hinzufügen',
    'addDish.name': 'Name des Gerichts',
    'addDish.namePlaceholder': 'z.B. Spaghetti Carbonara',
    'addDish.cuisine': 'Küche',
    'addDish.cuisinePlaceholder': 'Küche wählen',
    'addDish.category': 'Kategorie',
    'addDish.categoryPlaceholder': 'Kategorie wählen',
    'addDish.cookingTime': 'Kochzeit',
    'addDish.difficulty': 'Schwierigkeit',
    'addDish.ingredients': 'Zutaten',
    'addDish.ingredientPlaceholder': 'Zutat eingeben und Enter drücken',
    'addDish.ingredientNotFound': 'Keine Zutat gefunden. Drücke Enter um "{tag}" hinzuzufügen.',
    'addDish.existingIngredients': 'Vorhandene Zutaten',
    'addDish.cancel': 'Abbrechen',
    'addDish.submit': 'Gericht hinzufügen',
    'addDish.submitting': 'Wird hinzugefügt...',
    'addDish.success': 'Gericht erfolgreich hinzugefügt!',
    'addDish.error': 'Fehler beim Hinzufügen des Gerichts',
    'addDish.validationError': 'Fehlende Angaben',
    'addDish.validationDescription': 'Bitte fülle alle erforderlichen Felder aus',
    'addDish.validationPrompt': 'Bitte fülle folgende Felder aus:',
    'addDish.loginRequired': 'Login erforderlich',
    'addDish.loginDescription': 'Bitte melde dich an, um eigene Gerichte hinzuzufügen.',
    'addDish.required': '*',
    
    // Footer
    'footer.rights': 'Alle Rechte vorbehalten.',
    
    // Common
    'common.loading': 'Laden...',
    'common.error': 'Ein Fehler ist aufgetreten',
    'common.back': 'Zurück',
    'common.close': 'Schließen',
    
    // Cuisines
    'cuisine.italian': 'Italienisch',
    'cuisine.asian': 'Asiatisch',
    'cuisine.mediterranean': 'Mediterran',
    'cuisine.mexican': 'Mexikanisch',
    'cuisine.american': 'Amerikanisch',
    'cuisine.french': 'Französisch',
    'cuisine.greek': 'Griechisch',
    'cuisine.spanish': 'Spanisch',
    'cuisine.middle eastern': 'Naher Osten',
    'cuisine.japanese': 'Japanisch',
    'cuisine.thai': 'Thailändisch',
    'cuisine.indian': 'Indisch',
    'cuisine.chinese': 'Chinesisch',
    'cuisine.korean': 'Koreanisch',
    'cuisine.vietnamese': 'Vietnamesisch',
    
    // Difficulties
    'difficulty.easy': 'Einfach',
    'difficulty.medium': 'Mittel',
    'difficulty.hard': 'Schwer',
    
    /* Cooking time translations */
    'cookingTime.quick': 'Schnell',
    'cookingTime.medium': 'Mittel',
    'cookingTime.slow': 'Langsam',
    'cookingTime.long': 'Lang',
    
    // Categories
    'category.appetizer': 'Vorspeise',
    'category.main course': 'Hauptgericht',
    'category.dessert': 'Dessert',
    'category.breakfast': 'Frühstück',
    'category.lunch': 'Mittagessen',
    'category.dinner': 'Abendessen',
    'category.snack': 'Snack',
    'category.side dish': 'Beilage',
    'category.soup': 'Suppe',
    'category.salad': 'Salat',
    'category.beverage': 'Getränk',
    'category.pasta': 'Pasta',
    'category.pizza': 'Pizza',
    'category.rice': 'Reis',
    'category.meat': 'Fleisch',
    'category.chicken': 'Hähnchen',
    'category.noodles': 'Nudeln',
    'category.fish': 'Fisch',
    'category.seafood': 'Meeresfrüchte',
    'category.vegetable': 'Gemüse',

    // Ingredients
    'ingredient.pasta': 'Pasta',
    'ingredient.eggs': 'Eier',
    'ingredient.bacon': 'Speck',
    'ingredient.parmesan': 'Parmesan',
    'ingredient.cream': 'Sahne',
    'ingredient.dough': 'Teig',
    'ingredient.tomatoes': 'Tomaten',
    'ingredient.mozzarella': 'Mozzarella',
    'ingredient.basil': 'Basilikum',
    'ingredient.rice': 'Reis',
    'ingredient.mushrooms': 'Pilze',
    'ingredient.white wine': 'Weißwein',
    'ingredient.onion': 'Zwiebel',
    'ingredient.ground beef': 'Rinderhackfleisch',
    'ingredient.cheese': 'Käse',
    'ingredient.milk': 'Milch',
    'ingredient.veal': 'Kalbfleisch',
    'ingredient.vegetables': 'Gemüse',
    'ingredient.chili': 'Chili',
    'ingredient.garlic': 'Knoblauch',
    'ingredient.olive oil': 'Olivenöl',
    'ingredient.chicken': 'Hähnchen',
    'ingredient.breadcrumbs': 'Semmelbrösel',
    'ingredient.gnocchi': 'Gnocchi',
    'ingredient.pine nuts': 'Pinienkerne',
    'ingredient.butter': 'Butter',
    'ingredient.beans': 'Bohnen',
    'ingredient.herbs': 'Kräuter',
    'ingredient.beef': 'Rindfleisch',
    'ingredient.soy sauce': 'Sojasauce',
    'ingredient.sugar': 'Zucker',
    'ingredient.ginger': 'Ingwer',
    'ingredient.noodles': 'Nudeln',
    'ingredient.shrimp': 'Garnelen',
    'ingredient.peanuts': 'Erdnüsse',
    'ingredient.lime': 'Limette',
    'ingredient.pork': 'Schweinefleisch',
    'ingredient.pineapple': 'Ananas',
    'ingredient.bell peppers': 'Paprika',
    'ingredient.vinegar': 'Essig',
    'ingredient.yogurt': 'Joghurt',
    'ingredient.spices': 'Gewürze',
    'ingredient.curry paste': 'Currypaste',
    'ingredient.coconut milk': 'Kokosmilch',
    'ingredient.dumplings': 'Teigtaschen',
    'ingredient.peanut sauce': 'Erdnusssauce',
    'ingredient.skewers': 'Spieße',
    'ingredient.miso paste': 'Miso-Paste',
    'ingredient.tofu': 'Tofu',
    'ingredient.seaweed': 'Seetang',
    'ingredient.scallions': 'Frühlingszwiebeln',
    'ingredient.broth': 'Brühe',
    'ingredient.red wine': 'Rotwein',
    'ingredient.carrots': 'Karotten',
    'ingredient.flour': 'Mehl',
    'ingredient.lemon': 'Zitrone',
    'ingredient.saffron': 'Safran',
    'ingredient.seafood': 'Meeresfrüchte',
    'ingredient.potatoes': 'Kartoffeln',
    'ingredient.beer': 'Bier',
    'ingredient.oil': 'Öl',
    'ingredient.eggplant': 'Aubergine',
    'ingredient.ground lamb': 'Lammhackfleisch',
    'ingredient.gravy': 'Soße',
    'ingredient.fish': 'Fisch',
    'ingredient.shellfish': 'Schalentiere',
    'ingredient.tomato sauce': 'Tomatensauce',
    'ingredient.paprika': 'Paprika',
    'ingredient.pork ribs': 'Schweinerippchen',
    'ingredient.bbq sauce': 'BBQ-Sauce',
    'ingredient.brown sugar': 'Brauner Zucker',
    'ingredient.bread': 'Brot',
    'ingredient.lettuce': 'Salat',
    'ingredient.hot sauce': 'Scharfe Sauce',
    'ingredient.celery': 'Sellerie',
    'ingredient.onions': 'Zwiebeln',
    'ingredient.ketchup': 'Ketchup',
    'ingredient.clams': 'Muscheln',
    'ingredient.pork shoulder': 'Schweineschulter',
    'ingredient.sausage': 'Wurst',
    'ingredient.balsamic': 'Balsamico',
    'ingredient.curry powder': 'Currypulver',
    'ingredient.quinoa': 'Quinoa',
    'ingredient.tahini': 'Tahini',
    'ingredient.seeds': 'Samen',
    'ingredient.chickpeas': 'Kichererbsen',
    'ingredient.salmon': 'Lachs',
    'ingredient.tortillas': 'Tortillas',
    'ingredient.cabbage': 'Kohl',
    'ingredient.crab': 'Krabbe',
    'ingredient.mayonnaise': 'Mayonnaise',
    'ingredient.poblano peppers': 'Poblano-Paprika',
    'ingredient.cilantro': 'Koriander',
    'ingredient.dried fruits': 'Trockenfrüchte',
    'ingredient.couscous': 'Couscous',
    'ingredient.pita': 'Pita',
    'ingredient.black beans': 'Schwarze Bohnen',
    'ingredient.avocado': 'Avocado',
    'ingredient.zucchini': 'Zucchini',
    'ingredient.lamb': 'Lamm',
    'ingredient.mustard': 'Senf',
    'ingredient.brandy': 'Brandy',
    'ingredient.enchilada sauce': 'Enchilada-Sauce',
    'ingredient.caesar dressing': 'Caesar-Dressing',
    'ingredient.croutons': 'Croutons',
    'ingredient.cod': 'Kabeljau',
    'ingredient.ground turkey': 'Putenhackfleisch',
    'ingredient.cucumbers': 'Gurken',
    'ingredient.olives': 'Oliven',
    'ingredient.feta cheese': 'Feta-Käse',
    'ingredient.chicken wings': 'Chicken Wings',
  },
  en: {
    // Navigation
    'nav.brand': 'The Pantry',
    'nav.dishCollection': 'Dish Collection',
    'nav.weeklyPlanner': 'Weekly Planner',
    'nav.hello': 'Hello',
    'nav.logout': 'Logout',
    'nav.login': 'Login',
    
    // Hero Section
    'hero.title': 'Welcome to The Pantry',
    'hero.subtitle': 'Your culinary journey starts here. Discover delicious recipes, plan your meals, and get inspired by our selection.',
    'hero.cta': 'Explore Recipes',
    
    // Categories
    'categories.title': 'Discover Dishes',
    'categories.dishCollection.title': 'Dish Collection',
    'categories.dishCollection.description': 'Browse our complete collection of delicious dishes',
    'categories.dishOfDay.title': 'Dish of the Day',
    'categories.dishOfDay.description': 'Discover today\'s special dish',
    'categories.ingredientFinder.title': 'Ingredient Finder',
    'categories.ingredientFinder.description': 'Find recipes with your available ingredients',
    'categories.weeklyCalendar.title': 'Weekly Calendar',
    'categories.weeklyCalendar.description': 'Plan and manage your weekly meals',
    
    // Dish Library
    'dishLibrary.title': 'Dish Collection',
    'dishLibrary.search': 'Search dishes...',
    'dishLibrary.filters.cuisine': 'Cuisine',
    'dishLibrary.filters.cookingTime': 'Cooking Time',
    'dishLibrary.filters.difficulty': 'Difficulty',
    'dishLibrary.filters.category': 'Category',
    'dishLibrary.filters.all': 'All',
    'dishLibrary.filters.quick': 'Quick (<30 min)',
    'dishLibrary.filters.medium': 'Medium (30-60 min)',
    'dishLibrary.filters.long': 'Long (>60 min)',
    'dishLibrary.filters.easy': 'Easy',
    'dishLibrary.filters.hard': 'Hard',
    'dishLibrary.clearFilters': 'Clear Filters',
    'dishLibrary.results': 'dishes found',
    'dishLibrary.noResults': 'No dishes found',
    'dishLibrary.noResultsDescription': 'Try different search terms or clear the filters.',
    
    // Dish of the Day
    'dishOfDay.title': 'Dish of the Day',
    'dishOfDay.subtitle': 'Today we recommend this special dish',
    'dishOfDay.cookingTime': 'Cooking Time',
    'dishOfDay.difficulty': 'Difficulty',
    'dishOfDay.cuisine': 'Cuisine',
    'dishOfDay.category': 'Category',
    'dishOfDay.ingredients': 'Ingredients',
    
    // Ingredient Finder
    'ingredientFinder.title': 'Ingredient Finder',
    'ingredientFinder.subtitle': 'Select your available ingredients and discover matching dishes',
    'ingredientFinder.search': 'Search ingredients...',
    'ingredientFinder.selected': 'Selected Ingredients',
    'ingredientFinder.clear': 'Clear All',
    'ingredientFinder.results': 'Matching Dishes',
    'ingredientFinder.noIngredients': 'No ingredients selected',
    'ingredientFinder.selectIngredients': 'Select ingredients to find matching dishes.',
    
    // Weekly Calendar
    'weeklyCalendar.title': 'Weekly Calendar',
    'weeklyCalendar.subtitle': 'Plan your meals for the week',
    'weeklyCalendar.save': 'Save Weekly Plan',
    'weeklyCalendar.clear': 'Clear Week',
    'weeklyCalendar.connectSupabase': 'To save your weekly plan, you need to log in.',
    'weeklyCalendar.loginRequired': 'Login Required',
    'weeklyCalendar.saved': 'Weekly plan saved successfully!',
    'weeklyCalendar.cleared': 'Weekly plan cleared successfully!',
    'weeklyCalendar.error': 'Error saving weekly plan',
    'weeklyCalendar.days.monday': 'Monday',
    'weeklyCalendar.days.tuesday': 'Tuesday',
    'weeklyCalendar.days.wednesday': 'Wednesday',
    'weeklyCalendar.days.thursday': 'Thursday',
    'weeklyCalendar.days.friday': 'Friday',
    'weeklyCalendar.days.saturday': 'Saturday',
    'weeklyCalendar.days.sunday': 'Sunday',
    'weeklyCalendar.selectDish': 'Select dish...',
    'weeklyCalendar.personal': 'Personal Calendar',
    'weeklyCalendar.selectGroup': 'Select Group',
    
    // Groups
    'groups.title': 'My Groups',
    'groups.subtitle': 'Manage your groups and share weekly plans',
    'groups.createGroup': 'Create New Group',
    'groups.joinGroup': 'Join Group',
    'groups.myGroups': 'My Groups',
    'groups.noGroups': 'No Groups',
    'groups.noGroupsDescription': 'Create a new group or join with an invite code.',
    'groups.members': 'Members',
    'groups.inviteCode': 'Invite Code',
    'groups.copyCode': 'Copy Code',
    'groups.codeCopied': 'Code copied!',
    'groups.creator': 'Creator',
    'groups.member': 'Member',
    'groups.leaveGroup': 'Leave Group',
    'groups.deleteGroup': 'Delete Group',
    'groups.leaveConfirm': 'Are you sure you want to leave this group?',
    'groups.deleteConfirm': 'Are you sure you want to delete this group? This cannot be undone.',
    'groups.left': 'Successfully left group',
    'groups.deleted': 'Group successfully deleted',
    'groups.error': 'Error loading groups',
    
    // Create Group Dialog
    'createGroup.title': 'Create New Group',
    'createGroup.description': 'Create a group to share weekly plans with others.',
    'createGroup.nameLabel': 'Group Name',
    'createGroup.namePlaceholder': 'e.g. Family, Roommates, Friends',
    'createGroup.cancel': 'Cancel',
    'createGroup.create': 'Create',
    'createGroup.success': 'Group created successfully!',
    'createGroup.error': 'Error creating group',
    
    // Join Group Dialog
    'joinGroup.title': 'Join Group',
    'joinGroup.description': 'Enter an invite code to join a group.',
    'joinGroup.codeLabel': 'Invite Code',
    'joinGroup.codePlaceholder': 'Enter the code',
    'joinGroup.cancel': 'Cancel',
    'joinGroup.join': 'Join',
    'joinGroup.success': 'Successfully joined group!',
    'joinGroup.invalidCode': 'Invalid invite code',
    'joinGroup.alreadyMember': 'You are already a member of this group',
    'joinGroup.error': 'Error joining group',
    
    // Auth
    'auth.title': 'Authentication',
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.loginButton': 'Login',
    'auth.signupButton': 'Sign Up',
    'auth.switchToSignup': 'Don\'t have an account? Sign up',
    'auth.switchToLogin': 'Already have an account? Login',
    'auth.loginSuccess': 'Successfully logged in!',
    'auth.signupSuccess': 'Successfully signed up!',
    'auth.error': 'Authentication failed',
    'auth.backToHome': 'Back to Home',
    
    // Add Dish Dialog
    'addDish.button': 'Add Custom Dish',
    'addDish.title': 'Add New Dish',
    'addDish.name': 'Dish Name',
    'addDish.namePlaceholder': 'e.g. Spaghetti Carbonara',
    'addDish.cuisine': 'Cuisine',
    'addDish.cuisinePlaceholder': 'Select cuisine',
    'addDish.category': 'Category',
    'addDish.categoryPlaceholder': 'Select category',
    'addDish.cookingTime': 'Cooking Time',
    'addDish.difficulty': 'Difficulty',
    'addDish.ingredients': 'Ingredients',
    'addDish.ingredientPlaceholder': 'Enter ingredient and press Enter',
    'addDish.ingredientNotFound': 'No ingredient found. Press Enter to add "{tag}".',
    'addDish.existingIngredients': 'Existing Ingredients',
    'addDish.cancel': 'Cancel',
    'addDish.submit': 'Add Dish',
    'addDish.submitting': 'Adding...',
    'addDish.success': 'Dish added successfully!',
    'addDish.error': 'Error adding dish',
    'addDish.validationError': 'Missing Information',
    'addDish.validationDescription': 'Please fill in all required fields',
    'addDish.validationPrompt': 'Please fill in the following fields:',
    'addDish.loginRequired': 'Login Required',
    'addDish.loginDescription': 'Please log in to add custom dishes.',
    'addDish.required': '*',
    
    // Footer
    'footer.rights': 'All rights reserved.',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.back': 'Back',
    'common.close': 'Close',
    
    // Cuisines
    'cuisine.italian': 'Italian',
    'cuisine.asian': 'Asian',
    'cuisine.mediterranean': 'Mediterranean',
    'cuisine.mexican': 'Mexican',
    'cuisine.american': 'American',
    'cuisine.french': 'French',
    'cuisine.greek': 'Greek',
    'cuisine.spanish': 'Spanish',
    'cuisine.middle eastern': 'Middle Eastern',
    'cuisine.japanese': 'Japanese',
    'cuisine.thai': 'Thai',
    'cuisine.indian': 'Indian',
    'cuisine.chinese': 'Chinese',
    'cuisine.korean': 'Korean',
    'cuisine.vietnamese': 'Vietnamese',
    
    // Difficulties
    'difficulty.easy': 'Easy',
    'difficulty.medium': 'Medium',
    'difficulty.hard': 'Hard',
    
    /* Cooking time translations */
    'cookingTime.quick': 'Quick',
    'cookingTime.medium': 'Medium',
    'cookingTime.slow': 'Slow',
    'cookingTime.long': 'Long',
    
    // Categories
    'category.appetizer': 'Appetizer',
    'category.main course': 'Main Course',
    'category.dessert': 'Dessert',
    'category.breakfast': 'Breakfast',
    'category.lunch': 'Lunch',
    'category.dinner': 'Dinner',
    'category.snack': 'Snack',
    'category.side dish': 'Side Dish',
    'category.soup': 'Soup',
    'category.salad': 'Salad',
    'category.beverage': 'Beverage',
    'category.pasta': 'Pasta',
    'category.pizza': 'Pizza',
    'category.rice': 'Rice',
    'category.meat': 'Meat',
    'category.chicken': 'Chicken',
    'category.noodles': 'Noodles',
    'category.fish': 'Fish',
    'category.seafood': 'Seafood',
    'category.vegetable': 'Vegetable',

    // Ingredients
    'ingredient.pasta': 'Pasta',
    'ingredient.eggs': 'Eggs',
    'ingredient.bacon': 'Bacon',
    'ingredient.parmesan': 'Parmesan',
    'ingredient.cream': 'Cream',
    'ingredient.dough': 'Dough',
    'ingredient.tomatoes': 'Tomatoes',
    'ingredient.mozzarella': 'Mozzarella',
    'ingredient.basil': 'Basil',
    'ingredient.rice': 'Rice',
    'ingredient.mushrooms': 'Mushrooms',
    'ingredient.white wine': 'White Wine',
    'ingredient.onion': 'Onion',
    'ingredient.ground beef': 'Ground Beef',
    'ingredient.cheese': 'Cheese',
    'ingredient.milk': 'Milk',
    'ingredient.veal': 'Veal',
    'ingredient.vegetables': 'Vegetables',
    'ingredient.chili': 'Chili',
    'ingredient.garlic': 'Garlic',
    'ingredient.olive oil': 'Olive Oil',
    'ingredient.chicken': 'Chicken',
    'ingredient.breadcrumbs': 'Breadcrumbs',
    'ingredient.gnocchi': 'Gnocchi',
    'ingredient.pine nuts': 'Pine Nuts',
    'ingredient.butter': 'Butter',
    'ingredient.beans': 'Beans',
    'ingredient.herbs': 'Herbs',
    'ingredient.beef': 'Beef',
    'ingredient.soy sauce': 'Soy Sauce',
    'ingredient.sugar': 'Sugar',
    'ingredient.ginger': 'Ginger',
    'ingredient.noodles': 'Noodles',
    'ingredient.shrimp': 'Shrimp',
    'ingredient.peanuts': 'Peanuts',
    'ingredient.lime': 'Lime',
    'ingredient.pork': 'Pork',
    'ingredient.pineapple': 'Pineapple',
    'ingredient.bell peppers': 'Bell Peppers',
    'ingredient.vinegar': 'Vinegar',
    'ingredient.yogurt': 'Yogurt',
    'ingredient.spices': 'Spices',
    'ingredient.curry paste': 'Curry Paste',
    'ingredient.coconut milk': 'Coconut Milk',
    'ingredient.dumplings': 'Dumplings',
    'ingredient.peanut sauce': 'Peanut Sauce',
    'ingredient.skewers': 'Skewers',
    'ingredient.miso paste': 'Miso Paste',
    'ingredient.tofu': 'Tofu',
    'ingredient.seaweed': 'Seaweed',
    'ingredient.scallions': 'Scallions',
    'ingredient.broth': 'Broth',
    'ingredient.red wine': 'Red Wine',
    'ingredient.carrots': 'Carrots',
    'ingredient.flour': 'Flour',
    'ingredient.lemon': 'Lemon',
    'ingredient.saffron': 'Saffron',
    'ingredient.seafood': 'Seafood',
    'ingredient.potatoes': 'Potatoes',
    'ingredient.beer': 'Beer',
    'ingredient.oil': 'Oil',
    'ingredient.eggplant': 'Eggplant',
    'ingredient.ground lamb': 'Ground Lamb',
    'ingredient.gravy': 'Gravy',
    'ingredient.fish': 'Fish',
    'ingredient.shellfish': 'Shellfish',
    'ingredient.tomato sauce': 'Tomato Sauce',
    'ingredient.paprika': 'Paprika',
    'ingredient.pork ribs': 'Pork Ribs',
    'ingredient.bbq sauce': 'BBQ Sauce',
    'ingredient.brown sugar': 'Brown Sugar',
    'ingredient.bread': 'Bread',
    'ingredient.lettuce': 'Lettuce',
    'ingredient.hot sauce': 'Hot Sauce',
    'ingredient.celery': 'Celery',
    'ingredient.onions': 'Onions',
    'ingredient.ketchup': 'Ketchup',
    'ingredient.clams': 'Clams',
    'ingredient.pork shoulder': 'Pork Shoulder',
    'ingredient.sausage': 'Sausage',
    'ingredient.balsamic': 'Balsamic',
    'ingredient.curry powder': 'Curry Powder',
    'ingredient.quinoa': 'Quinoa',
    'ingredient.tahini': 'Tahini',
    'ingredient.seeds': 'Seeds',
    'ingredient.chickpeas': 'Chickpeas',
    'ingredient.salmon': 'Salmon',
    'ingredient.tortillas': 'Tortillas',
    'ingredient.cabbage': 'Cabbage',
    'ingredient.crab': 'Crab',
    'ingredient.mayonnaise': 'Mayonnaise',
    'ingredient.poblano peppers': 'Poblano Peppers',
    'ingredient.cilantro': 'Cilantro',
    'ingredient.dried fruits': 'Dried Fruits',
    'ingredient.couscous': 'Couscous',
    'ingredient.pita': 'Pita',
    'ingredient.black beans': 'Black Beans',
    'ingredient.avocado': 'Avocado',
    'ingredient.zucchini': 'Zucchini',
    'ingredient.lamb': 'Lamb',
    'ingredient.mustard': 'Mustard',
    'ingredient.brandy': 'Brandy',
    'ingredient.enchilada sauce': 'Enchilada Sauce',
    'ingredient.caesar dressing': 'Caesar Dressing',
    'ingredient.croutons': 'Croutons',
    'ingredient.cod': 'Cod',
    'ingredient.ground turkey': 'Ground Turkey',
    'ingredient.cucumbers': 'Cucumbers',
    'ingredient.olives': 'Olives',
    'ingredient.feta cheese': 'Feta Cheese',
    'ingredient.chicken wings': 'Chicken Wings',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'de';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  const translateField = (type: 'cuisine' | 'difficulty' | 'cookingTime' | 'category' | 'ingredient', value: string): string => {
    const key = `${type}.${value.toLowerCase()}`;
    const translated = t(key);
    // If no translation found, return original value
    return translated === key ? value : translated;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, translateField }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};